# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-18.04
  variables:
  imageName: 'database'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    repository: database/repository
    containerRegistry: harbor-database
    Dockerfile: Dockerfile
    tags: $(build.buildId)
- script: docker login demo.goharbor.io/ --username=albertoraaz --password=Ven320wl8ven!
- task: Docker@2
  displayName: Push an image
  inputs: 
    repository: demo.goharbor.io/database/repository
- script: docker push demo.goharbor.io/database/repository:$(build.buildId) 