version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: database_mysql
    ports:
      - 3307:3306
    volumes:
      - ./migrations/sqls/schema-test.sql:/docker-entrypoint-initdb.d/schema-test.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
networks: 
  default:
    name: database